environment:
  name: dev
  project: cdf-bootcamp-72-test # Your CDF project
  type: dev #prod, staging or dev
  selected:
  - modules/data_foundation
  - modules/ice_cream_api
  - modules/uc_oee

variables:
  CDF_PROJECT: cdf-bootcamp-72-test
  IDP_CLIENT_ID: ${IDP_CLIENT_ID}
  IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
  IDP_TENANT_ID: 16e3985b-ebe8-4e24-9da4-933e21a9fc81 # Since we all have the same tenant, this number does not change
  CDF_URL: https://westeurope-1.cognitedata.com # This is related to the cluster where the CDF project is hosted.
  IDP_SCOPES: https://westeurope-1.cognitedata.com/.default

  # Groups
  data_developer_source_id: 2c746bbe-9e0e-4153-8665-f51abb2089c5 # data_explorer??
  oee_data_pipeline_source_id: 55a04990-7a73-4e8f-9191-ae6849efebe5
  readwrite_source_id: 7b93647b-7bec-4564-95ad-b2a246bedb11
  readonly_source_id: 9842bd92-7be9-402b-9a07-742bf49ede0a
  icapi_extractors_source_id: 48121077-204e-418e-abc5-7020cca8a5fe

  # Client Ids
  sp_oee_client_id: 4953481f-bfdc-4374-9374-df9757781d20
  sp_oee_client_secret: ${IDP_CLIENT_SECRET}
  icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
  icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}


  modules:
    icapi_ds_external_id: ds_ice_cream_api
    uc_oee_ds_external_id: ds_uc_oee
